import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="flex w-screen p-7 bg-yellow-300  ">
          <li className="text-center flex-1 text-xl">
            <a href="/login">Login</a>
          </li>
          <li className="text-center flex-1 text-xl">
            <a href="/signup">Signup</a>
          </li>
          <li className="text-center flex-1 text-xl">
            <a href="/todo">Todo</a>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
